title: Diode Foundation
description: Our purpose is to deploy and sustain worldwide secure Internet communications via the Diode Network.
theme: just-the-docs

url: https://diode.foundation

aux_links:
  Diode: https://diode.io